<div style="background-image: url('https://www.semana.com/resizer/nGgx6guzYcV1U7tLC5oAC4kl3wY=/1280x720/smart/filters:format(jpg):quality(80)/cloudfront-us-east-1.images.arcpublishing.com/semana/YDT5DSVK7FCHLLTFKH42V3KICQ.jpg'); background-size: cover; background-position: bottom; padding: 20px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
    <h1 style="text-align: center; font-size: 38px; color: black; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3); margin-bottom: 10px;"> ⛽Petrol Price Analysis ⛽📈</h1>
    <p style="text-align: center; font-size: 20px; color: black;">Explore data, discover insights, and unleash the power of analysis.</p>
</div>

<div style="background-color: white; padding: 20px; color: #11aeec; border-radius: 10px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
    <h1 style="font-family: comic sans MS; font-size: 28px;"> <strong>What is Petroleum ?</strong></h1>
    <p style="text-align: left; font-size: 18px; color: #11aeec;">1. Petroleum is a natural liquid formed from ancient plankton under heat and pressure in Earth's crust.<br>
2. Its use dates back over 5000 years, for fires and warfare in early history.<br>
3. While initially irrelevant to the world economy, its importance grew in the 19th century.<br>
4. Whale oil and wood remained dominant for lighting and heating until kerosene, derived from crude oil, became popular.<br>
5. By the 20th century, petroleum became the most valuable commodity traded globally.</p>
</div>

<img src="https://www.smfmotor.com/wp-content/uploads/2020/06/woman-fills-petrol-into-the-car-at-a-gas-station-PSQ8JYV-smaller-.jpg" alt="Petrol Image" style="box-shadow: 5px 5px 5px grey;">

In [1]:
import pandas as pd 
import plotly.express as px

In [2]:
df = pd.read_csv('/kaggle/input/top-15-indian-states-petrol-prices-2017-2022/petrol_price.csv')

In [3]:
df.sample(5)

,date,Maharashtra,Haryana,Delhi,Gujarat,Karnataka,Telangana,Rajasthan,Punjab,West_bengal,Tamil Nadu,Uttar Pradesh,Madhya Pradesh,Kerala,Assam,Bihar
5,2017_Nov,76.25,68.70,69.14,68.37,70.21,73.20,71.61,74.13,71.90,71.65,71.51,73.71,72.91,71.04,73.49
46,2021_Dec,109.98,95.27,95.41,95.35,100.58,108.20,107.06,94.94,104.67,101.40,95.28,107.23,106.36,94.58,105.90
62,2022_Jun,97.28,90.27,89.62,92.38,87.89,97.82,93.72,86.55,92.76,94.24,89.76,93.90,96.52,83.94,94.04
44,2021_Apr,96.98,88.02,90.56,87.90,93.59,94.16,97.08,91.54,90.77,92.58,88.68,98.58,92.44,87.23,92.89
63,2022_Mar,109.98,95.27,95.41,95.35,100.58,108.20,107.06,94.94,104.67,101.40,95.28,107.23,106.36,94.58,105.90

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            67 non-null     object
 1   Maharashtra     67 non-null     float64
 2    Haryana        67 non-null     float64
 3   Delhi           67 non-null     float64
 4   Gujarat         67 non-null     float64
 5   Karnataka       67 non-null     float64
 6   Telangana       67 non-null     float64
 7   Rajasthan       67 non-null     float64
 8   Punjab          67 non-null     float64
 9   West_bengal     67 non-null     float64
 10  Tamil Nadu      67 non-null     float64
 11   Uttar Pradesh  67 non-null     float64
 12  Madhya Pradesh  67 non-null     float64
 13  Kerala          67 non-null     float64
 14  Assam           67 non-null     float64
 15  Bihar           67 non-null     float64
dtypes: float64(15), object(1)
memory usage: 8.5+ KB

In [5]:
df.describe()

,Maharashtra,Haryana,Delhi,Gujarat,Karnataka,Telangana,Rajasthan,Punjab,West_bengal,Tamil Nadu,Uttar Pradesh,Madhya Pradesh,Kerala,Assam,Bihar
count,67.000000,67.000000,67.000000,67.000000,67.000000,67.000000,67.000000,67.000000,67.000000,67.000000,67.000000,67.000000,67.000000,67.000000,67.000000
mean,89.094030,80.561343,81.278209,79.951343,84.020597,86.935672,86.625373,83.088955,84.542836,84.281940,81.551045,88.570597,85.668657,82.019254,86.291343
std,13.338161,11.747156,12.036261,11.988457,13.031010,14.264798,15.036667,11.015556,13.359466,12.260133,10.898700,14.080720,13.778086,10.526686,13.352867
min,74.300000,62.680000,63.090000,64.770000,64.240000,67.020000,65.770000,67.930000,66.140000,65.460000,66.530000,69.620000,66.930000,65.830000,65.930000
25%,78.350000,71.390000,71.595000,70.210000,73.745000,76.020000,74.170000,73.510000,74.030000,74.480000,72.150000,77.070000,75.025000,72.530000,75.995000
50%,83.760000,76.520000,76.310000,75.680000,78.770000,80.900000,79.260000,81.490000,79.200000,79.260000,77.110000,83.220000,79.470000,78.510000,82.050000
75%,99.145000,91.025000,92.830000,92.030000,95.930000,98.010000,99.370000,93.540000,93.630000,95.115000,90.705000,100.910000,96.495000,89.600000,95.340000
max,120.510000,106.620000,109.690000,106.530000,113.560000,119.490000,118.030000,110.610000,115.120000,110.850000,106.610000,118.460000,117.190000,105.740000,116.230000

<div style="background-color: #17a526; padding: 30px; border-radius: 10px; box-shadow: 0 8px 12px rgba(0, 0, 0, 0.3); margin-top: 30px; text-align: center;">
    <h1 style="color: #ffffff; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.4); font-size: 38; margin-bottom: 25px;"><strong>Data Analysis</strong></h1>
</div>

In [6]:
average_prices = df.drop('date', axis=1).mean(axis=0).reset_index()
average_prices.columns = ['State', 'Average Petrol Price']

highest_avg_state = average_prices.loc[average_prices['Average Petrol Price'].idxmax(), 'State']
fig = px.bar(average_prices, x='State', y='Average Petrol Price', title='Average Petrol Price Over the Last 5 Years',
             labels={'Average Petrol Price': 'Average Petrol Price (INR)'})

fig.update_layout(
    plot_bgcolor='black',  
    paper_bgcolor='black',  
    font=dict(color='white'),  
    xaxis=dict(tickfont=dict(color='white')),  
    yaxis=dict(tickfont=dict(color='white'), showgrid=False), 
    annotations=[dict(x=highest_avg_state, y=average_prices['Average Petrol Price'].max(),
                      text=f'Highest Avg ({highest_avg_state})', showarrow=True, arrowhead=5,
                      ax=0, ay=-60, font=dict(size=18, color='white'),
                      arrowcolor='white')] 
)

fig.show()

In [7]:
df_maharashtra_delhi = df[['date', 'Maharashtra', 'Delhi']]

df_maharashtra_delhi = pd.melt(df_maharashtra_delhi, id_vars='date', var_name='State', value_name='Petrol Price')


fig = px.line(df_maharashtra_delhi, x='date', y='Petrol Price', color='State',
              title='Petrol Prices Comparison Between Maharashtra and Delhi',
              labels={'Petrol Price': 'Petrol Price (INR)', 'date': 'Month'})

fig.update_layout(
    plot_bgcolor='black',  
    paper_bgcolor='black',  
    font=dict(color='white'),  
    xaxis=dict(tickfont=dict(color='white'), title=''),  
    yaxis=dict(tickfont=dict(color='white'), showgrid=False),  
    xaxis_tickmode='array',
    xaxis_tickvals=[]  
)

fig.show()

In [8]:
fig1 = px.line(df, x='date', y=df.columns[1:], title='Petrol Prices Trend Over 5 Years')

fig1.update_layout(
    plot_bgcolor='black', 
    paper_bgcolor='black',  
    font=dict(color='white'),  
    xaxis=dict(tickfont=dict(color='white'), title='', tickmode='array', tickvals=[]), 
    yaxis=dict(tickfont=dict(color='white'), showgrid=False),
)

fig1.show()

In [9]:
fig2 = px.box(df, x='date', y=df.columns[1:], title='Petrol Prices Comparison Among States')

fig2.update_layout(
    plot_bgcolor='black', 
    paper_bgcolor='black',  
    font=dict(color='white'),  
    xaxis=dict(tickfont=dict(color='white'), title='',tickmode='array', tickvals=[]),  
    yaxis=dict(tickfont=dict(color='white'), showgrid=False),   
)

fig2.show()

In [10]:
fig5 = px.scatter(df, x='date', y=df.columns[1:], title='State-specific Fluctuations in Petrol Prices',
                  labels={'value': 'Petrol Price', 'date': 'Month'})

fig5.update_layout(
    plot_bgcolor='black',  
    paper_bgcolor='black',  
    font=dict(color='white'), 
    xaxis=dict(tickfont=dict(color='white'), title='', tickmode='array', tickvals=[]), 
    yaxis=dict(tickfont=dict(color='white'), showgrid=False),  
)

fig5.show()

In [11]:
numeric_columns = df.drop('date', axis=1)

correlation_matrix = numeric_columns.corr()
fig4 = px.imshow(correlation_matrix, x=numeric_columns.columns, y=numeric_columns.columns,
                 color_continuous_scale='Viridis', title='Correlation Matrix of Petrol Prices Across States')

fig4.update_layout(
    plot_bgcolor='black',  
    paper_bgcolor='black', 
    font=dict(color='white'), 
    xaxis=dict(tickfont=dict(color='white')), 
    yaxis=dict(tickfont=dict(color='white')),  
    coloraxis_colorbar=dict(title='Correlation', tickfont=dict(color='white')), 
)

fig4.show()

In [12]:

variance_prices = df.drop('date', axis=1).var(axis=0).reset_index()
variance_prices.columns = ['State', 'Petrol Price Variance']

highest_var_state = variance_prices.loc[variance_prices['Petrol Price Variance'].idxmax(), 'State']


fig = px.bar(variance_prices, x='State', y='Petrol Price Variance',
             title='Petrol Price Variance Over the Last 5 Years',
             labels={'Petrol Price Variance': 'Petrol Price Variance (INR^2)'})

fig.update_layout(
    plot_bgcolor='black',  
    paper_bgcolor='black', 
    font=dict(color='white'), 
    xaxis=dict(tickfont=dict(color='white')),  
    yaxis=dict(tickfont=dict(color='white'),showgrid=False),  
    annotations=[dict(x=highest_var_state, y=variance_prices['Petrol Price Variance'].max(),
                      text=f'Highest Variance ({highest_var_state})', showarrow=True, arrowhead=4,
                      ax=0, ay=-60, font=dict(size=18, color='white'),arrowcolor='white')],
    showlegend=False
)

fig.show()

In [13]:
correlation_data = df[['Maharashtra', 'Karnataka']]

correlation_matrix = correlation_data.corr()


fig = px.imshow(correlation_matrix, x=correlation_data.columns, y=correlation_data.columns,
                color_continuous_scale='Viridis', title='Correlation Between Petrol Prices in Maharashtra and Karnataka')


fig.update_layout(
    plot_bgcolor='black',  
    paper_bgcolor='black',  
    font=dict(color='white'),  
    xaxis=dict(tickfont=dict(color='white')),  
    yaxis=dict(tickfont=dict(color='white')),  
    coloraxis_colorbar=dict(title='Correlation', tickfont=dict(color='white')),
)

fig.show()

<div style="background-color: white; padding: 20px; color: #17a526; border-radius: 10px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
    <h1 style="font-family: comic sans MS; font-size: 32px;"> <strong>Conclusion:</strong></h1>
    <p style="text-align: left; font-size: 18px; color: #17a526;">1. Petrol prices across states have consistently risen over the last 5 years, indicating a continuous upward trend.<br>
2. Maharashtra and Delhi show significant price fluctuations, possibly influenced by local factors like taxation and demand.<br>
3. The correlation matrix reveals similarities in petrol price movements between states, highlighting shared economic influences.<br>
4. Variance analysis identifies states with the highest price fluctuations, indicating regions with increased volatility.<br>
5. Box plot analysis illustrates the distribution of petrol prices, showcasing variations and potential economic disparities among states.</p>
</div>

<div style="background-color: white; padding: 20px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
    <h1 style="text-align: center; font-size: 28px; color: green; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3); margin-bottom: 10px;"><strong>Thank You for Exploring This Notebook! 😊If you enjoyed it and found value in the content, please consider giving it an Upvote. See You Soon</strong></h1>
</div>